version: 2
models:
  - name: stg_moco_retail
    description: "Raw MoCo retail sales exposed as a view via source()"

  - name: stg_moco_retail_typed
    description: "Auto-typed staging + derived sale_date"
