version: 2
models:
  - name: stg_moco_retail
    description: "Raw MoCo retail sales exposed as a view via source()."

  - name: stg_moco_retail_typed
    description: "Typed + renamed staging; derives sale_date from YEAR/MONTH."
    columns:
      - name: year_num
        description: "Calendar year as integer."
      - name: month_num
        description: "Calendar month number (1..12)."
        tests:
          - accepted_values:
              values: ["1","2","3","4","5","6","7","8","9","10","11","12"]
      - name: item_code
        description: "Raw 'ITEM CODE'."
        testss:
          - not_null
      - name: sale_date
        description: "Month start date from year/month."
        tests:
          - not_null